#include "deus.h"
#include <stdio.h>
#include <string.h>

typedef struct { unsigned hunts, releases; } State;
static int mock_hunt(void *context,const char *url,size_t length,DeusHostDocument *document,char *error,size_t error_cap){static const char body[]="<h1>X</h1>";State *state=(State*)context;(void)error;(void)error_cap;if(length!=11u||memcmp(url,"deus://test",11u))return 0;state->hunts++;document->data=body;document->length=sizeof(body)-1u;document->status=200u;return 1;}
static void mock_release(void *context,DeusHostDocument *document){State *state=(State*)context;state->releases++;memset(document,0,sizeof(*document));}
static int output_is(FILE *file,const char *expected){char text[64]={0};size_t length;rewind(file);length=fread(text,1u,sizeof(text)-1u,file);return length==strlen(expected)&&!memcmp(text,expected,length);}
int main(void){DeusInstruction pure_code[]={{DEUS_GENESIS,0u,0},{DEUS_CONST_I64,0u,42},{DEUS_EMIT,0u,0},{DEUS_CONST_BOOL,1u,0},{DEUS_EMIT,0u,0},{DEUS_HALT,0u,0}};DeusProgram pure={NULL,0u,pure_code,6u};DeusString strings[]={{"deus://test",11u},{"h1",2u}};DeusInstruction host_code[]={{DEUS_GENESIS,0u,0},{DEUS_FORK,0u,0},{DEUS_FORK,0u,0},{DEUS_JOIN,2u,0},{DEUS_REAP,1u,0},{DEUS_EMIT,0u,0},{DEUS_REAP,1u,0},{DEUS_EMIT,0u,0},{DEUS_HALT,0u,0}};DeusProgram retrieval={strings,2u,host_code,9u};State state={0};DeusHost host={DEUS_HOST_ABI_VERSION,DEUS_HOST_CAP_NETWORK,&state,mock_hunt,mock_release};FILE *output=tmpfile();if(!output)return 1;if(deus_vm_execute_program(&pure,output)||!output_is(output,"42true")){fclose(output);return 1;}fclose(output);output=tmpfile();if(!output)return 1;if(deus_vm_execute_program_with_host(&retrieval,output,&host)||!output_is(output,"X\nX\n")||state.hunts!=2u||state.releases!=2u){fclose(output);return 1;}fclose(output);puts("portable VM pure and synchronous host execution passed");return 0;}
