#include "deus.h"
#include "deus_json.h"
#include "deus_value.h"
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define STACK_MAX 1024u
#define RESPONSE_MAX (32u*1024u*1024u)
#define URL_MAX 8192u
typedef enum{V_DOC,V_TEXT,V_STRING,V_NULL,V_BOOL,V_I64,V_MANAGED,V_FUTURE}Kind;
typedef struct{Kind kind;char *data;size_t len;int64_t scalar;DeusValue managed;}Value;
typedef struct{const DeusHost *host;uint32_t retries;}Runtime;
static int fail(const char *m){fprintf(stderr,"deus: %s\n",m);return 1;}
static int file_write(void *c,const void *d,size_t n){return fwrite(d,1u,n,(FILE*)c)==n;}
static int sink_write(const DeusOutputSink *o,const void *d,size_t n){return!n||o->write(o->context,d,n);}
static void drop(Value *v){if(v->kind==V_DOC||v->kind==V_TEXT||v->kind==V_STRING||v->kind==V_FUTURE)free(v->data);else if(v->kind==V_MANAGED)deus_value_dispose(&v->managed);memset(v,0,sizeof(*v));}
static int clone(const Value *s,Value *o){*o=*s;if(s->kind==V_DOC||s->kind==V_TEXT||s->kind==V_STRING||s->kind==V_FUTURE){o->data=(char*)malloc(s->len+1u);if(!o->data)return 0;if(s->len)memcpy(o->data,s->data,s->len);o->data[s->len]=0;}else if(s->kind==V_MANAGED)deus_value_copy(&o->managed,&s->managed);return 1;}
static int to_managed(const Value *v,DeusValueContext *c,DeusValue *o){if(v->kind==V_MANAGED){deus_value_copy(o,&v->managed);return 1;}if(v->kind==V_NULL){*o=deus_value_null();return 1;}if(v->kind==V_BOOL){*o=deus_value_bool(v->scalar!=0);return 1;}if(v->kind==V_I64){*o=deus_value_i64(v->scalar);return 1;}return(v->kind==V_STRING||v->kind==V_TEXT)&&deus_value_string(c,v->data,v->len,o);}
static int from_managed(const DeusValue *v,Value *o){size_t n=0;const void *p;memset(o,0,sizeof(*o));if(v->kind==DEUS_VALUE_NULL){o->kind=V_NULL;return 1;}if(v->kind==DEUS_VALUE_BOOL){o->kind=V_BOOL;o->scalar=v->as.boolean;return 1;}if(v->kind==DEUS_VALUE_I64){o->kind=V_I64;o->scalar=v->as.integer;return 1;}if(v->kind==DEUS_VALUE_STRING){p=deus_value_data(v,&n);o->data=(char*)malloc(n+1u);if(!o->data)return 0;if(n)memcpy(o->data,p,n);o->data[n]=0;o->kind=V_STRING;o->len=n;return 1;}if(v->kind==DEUS_VALUE_LIST||v->kind==DEUS_VALUE_RECORD){o->kind=V_MANAGED;deus_value_copy(&o->managed,v);return 1;}return 0;}
static int hunt(Runtime *r,const char *url,size_t n,Value *o,char *e,size_t cap){DeusHostDocument d={0};uint32_t i;char *copy=NULL;const DeusHost *h=r->host;if(!deus_host_validate(h,DEUS_HOST_CAP_NETWORK,e,cap))return 0;for(i=0;i<=r->retries;i++){memset(&d,0,sizeof(d));if(cap)e[0]=0;if(h->hunt(h->context,url,n,&d,e,cap))break;}if(i>r->retries){if(cap&&!e[0])snprintf(e,cap,"host hunt failed");return 0;}if((!d.data&&d.length)||d.length>RESPONSE_MAX||d.status<200u||d.status>=300u)snprintf(e,cap,"%s",d.length>RESPONSE_MAX?"host response exceeds 32 MiB":d.status<200u||d.status>=300u?"host returned non-success status":"host returned invalid document");else{copy=(char*)malloc(d.length+1u);if(copy){if(d.length)memcpy(copy,d.data,d.length);copy[d.length]=0;*o=(Value){V_DOC,copy,d.length,0,{0}};}else snprintf(e,cap,"out of memory");}if(h->release_document)h->release_document(h->context,&d);return copy!=NULL;}
static char *reap(const char *h,size_t n,const char *s,size_t sn,size_t *outn){size_t i=0,u=0;char *o=(char*)malloc(n+2u);if(!o)return NULL;while(i+sn+2u<n){if(h[i]=='<'&&!memcmp(h+i+1,s,sn)&&(h[i+1+sn]=='>'||h[i+1+sn]==' ')){while(i<n&&h[i]!='>')i++;i++;while(i<n){if(h[i]=='<'&&i+sn+3u<n&&h[i+1]=='/'&&!memcmp(h+i+2,s,sn))break;if(h[i]=='<'){while(i<n&&h[i]!='>')i++;if(i<n)i++;}else o[u++]=h[i++];}o[u++]='\n';}else i++;}o[u]=0;*outn=u;return o;}
static int unreserved(unsigned char b){return(b>='A'&&b<='Z')||(b>='a'&&b<='z')||(b>='0'&&b<='9')||b=='-'||b=='.'||b=='_'||b=='~';}
static int encode(Value *v){static const char x[]="0123456789ABCDEF";char b[32];const char *p=v->data;size_t n=v->len,i,u=0;char *o;if(v->kind==V_I64){int z=snprintf(b,sizeof(b),"%lld",(long long)v->scalar);if(z<0)return 0;p=b;n=(size_t)z;}else if(v->kind==V_BOOL){p=v->scalar?"true":"false";n=v->scalar?4u:5u;}else if(v->kind!=V_STRING&&v->kind!=V_TEXT)return 0;if(n>URL_MAX/3u)return 0;o=(char*)malloc(n*3u+1u);if(!o)return 0;for(i=0;i<n;i++){unsigned char c=(unsigned char)p[i];if(unreserved(c))o[u++]=(char)c;else{o[u++]='%';o[u++]=x[c>>4];o[u++]=x[c&15u];}}o[u]=0;drop(v);*v=(Value){V_STRING,o,u,0,{0}};return 1;}
int deus_vm_execute_program_with_options(const DeusProgram *p,const DeusOutputSink *out,const DeusHost *host,const DeusExecutionOptions *options){Value st[STACK_MAX]={{0}},loc[DEUS_MAX_LOCALS]={{0}};unsigned char bound[DEUS_MAX_LOCALS]={0};Runtime rt={host,2u};DeusValueContext *ctx;size_t sp=0;uint32_t pc;uint64_t instructions=0u;int rc=0;char err[192]={0};if(!deus_validate_program(p,err,sizeof(err)))return fail(err);if(!out||out->abi_version!=DEUS_OUTPUT_ABI_VERSION||!out->write)return fail("invalid output sink");if(!options||options->abi_version!=DEUS_EXECUTION_ABI_VERSION||!options->instruction_limit||(options->deadline_ms&&!options->now_ms))return fail("invalid execution options");ctx=deus_value_context_create(NULL);if(!ctx)return fail("value context allocation failed");
for(pc=0;pc<p->code_count;pc++){DeusInstruction in;const char *a;size_t an;if(instructions++>=options->instruction_limit){rc=fail("instruction budget exhausted");break;}if(options->should_cancel&&options->should_cancel(options->context)){rc=fail("execution cancelled");break;}if(options->deadline_ms&&options->now_ms(options->context)>=options->deadline_ms){rc=fail("execution deadline exceeded");break;}in=p->code[pc];a=in.operand<p->string_count?p->strings[in.operand].data:"";an=in.operand<p->string_count?p->strings[in.operand].len:0u;
if(in.opcode==DEUS_OMNI||in.opcode==DEUS_GENESIS||in.opcode==DEUS_LIMIT||in.opcode==DEUS_BACKOFF||in.opcode==DEUS_RATE){}
else if(in.opcode==DEUS_RETRY)rt.retries=in.operand;
else if(in.opcode==DEUS_HUNT||in.opcode==DEUS_FORK){Value d;if(!hunt(&rt,a,an,&d,err,sizeof(err))){rc=fail(err);break;}d.kind=in.opcode==DEUS_FORK?V_FUTURE:V_DOC;st[sp++]=d;}
else if(in.opcode==DEUS_CONST){char *q=(char*)malloc(an+1u);if(!q){rc=fail("CONST allocation failed");break;}if(an)memcpy(q,a,an);q[an]=0;st[sp++]=(Value){V_STRING,q,an,0,{0}};}
else if(in.opcode==DEUS_CONST_NULL)st[sp++]=(Value){V_NULL,NULL,0,0,{0}};
else if(in.opcode==DEUS_CONST_BOOL)st[sp++]=(Value){V_BOOL,NULL,0,in.operand?1:0,{0}};
else if(in.opcode==DEUS_CONST_I64)st[sp++]=(Value){V_I64,NULL,0,in.immediate,{0}};
else if(in.opcode==DEUS_CONST_RECORD||in.opcode==DEUS_CONST_LIST){DeusValue v;int ok=in.opcode==DEUS_CONST_RECORD?deus_value_record(ctx,&v):deus_value_list(ctx,&v);if(!ok){rc=fail(deus_value_context_error(ctx));break;}st[sp]=(Value){0};st[sp].kind=V_MANAGED;st[sp++].managed=v;}
else if(in.opcode==DEUS_BIND){loc[in.operand]=st[--sp];memset(&st[sp],0,sizeof(st[sp]));bound[in.operand]=1;}
else if(in.opcode==DEUS_LOAD){if(!bound[in.operand]||!clone(&loc[in.operand],&st[sp])){rc=fail("invalid VM state at LOAD");break;}sp++;}
else if(in.opcode==DEUS_AWAIT)st[sp-1u].kind=V_DOC;
else if(in.opcode==DEUS_JOIN){size_t i;for(i=sp-in.operand;i<sp;i++)st[i].kind=V_DOC;}
else if(in.opcode==DEUS_REAP){Value v=st[--sp];size_t n;char *q=reap(v.data,v.len,a,an,&n);drop(&v);if(!q){rc=fail("REAP allocation failed");break;}st[sp++]=(Value){V_TEXT,q,n,0,{0}};}
else if(in.opcode==DEUS_JSON_PATH){DeusJsonScalar s;Value v=st[--sp];if(!deus_json_extract_scalar(v.data,v.len,a,an,&s,err,sizeof(err))){drop(&v);rc=fail(err);break;}drop(&v);if(s.kind==DEUS_JSON_STRING){st[sp++]=(Value){V_STRING,s.string,s.string_length,0,{0}};s.string=NULL;}else if(s.kind==DEUS_JSON_I64)st[sp++]=(Value){V_I64,NULL,0,s.integer,{0}};else if(s.kind==DEUS_JSON_BOOL)st[sp++]=(Value){V_BOOL,NULL,0,s.boolean?1:0,{0}};else st[sp++]=(Value){V_NULL,NULL,0,0,{0}};deus_json_scalar_dispose(&s);}
else if(in.opcode==DEUS_RECORD_SET||in.opcode==DEUS_LIST_PUSH){DeusValue item;Value *c=&st[sp-2u],*v=&st[sp-1u];int ok;if(!to_managed(v,ctx,&item)){rc=fail("invalid compound mutation");break;}ok=in.opcode==DEUS_RECORD_SET?deus_value_record_set(&c->managed,a,an,&item):deus_value_list_append(&c->managed,&item);deus_value_dispose(&item);if(!ok){rc=fail(deus_value_context_error(ctx));break;}drop(v);drop(c);sp-=2u;}
else if(in.opcode==DEUS_RECORD_GET||in.opcode==DEUS_RECORD_GET_OPTIONAL||in.opcode==DEUS_LIST_AT||in.opcode==DEUS_LIST_AT_OPTIONAL){int rec=in.opcode==DEUS_RECORD_GET||in.opcode==DEUS_RECORD_GET_OPTIONAL,opt=in.opcode==DEUS_RECORD_GET_OPTIONAL||in.opcode==DEUS_LIST_AT_OPTIONAL;const DeusValue *f=rec?deus_value_record_get(&st[sp-1u].managed,a,an):deus_value_list_at(&st[sp-1u].managed,in.operand);Value x;if(!f&&!opt){rc=fail(rec?"record field was not found":"list index is out of bounds");break;}if(!f){drop(&st[sp-1u]);st[sp-1u]=(Value){V_NULL,NULL,0,0,{0}};}else if(!from_managed(f,&x)){rc=fail("structured value cannot be loaded");break;}else{drop(&st[sp-1u]);st[sp-1u]=x;}}
else if(in.opcode==DEUS_BOOL_NOT)st[sp-1u].scalar=!st[sp-1u].scalar;
else if((in.opcode>=DEUS_EQUAL&&in.opcode<=DEUS_COALESCE)){Value r=st[--sp],l=st[--sp];int b=0;if(in.opcode==DEUS_COALESCE){if(l.kind==V_NULL){drop(&l);st[sp++]=r;}else{drop(&r);st[sp++]=l;}continue;}if(in.opcode==DEUS_BOOL_AND||in.opcode==DEUS_BOOL_OR)b=in.opcode==DEUS_BOOL_AND?(l.scalar&&r.scalar):(l.scalar||r.scalar);else if(in.opcode>=DEUS_LESS&&in.opcode<=DEUS_GREATER_EQUAL)b=in.opcode==DEUS_LESS?l.scalar<r.scalar:in.opcode==DEUS_LESS_EQUAL?l.scalar<=r.scalar:in.opcode==DEUS_GREATER?l.scalar>r.scalar:l.scalar>=r.scalar;else{int eq=l.kind==r.kind;if(eq&&(l.kind==V_BOOL||l.kind==V_I64))eq=l.scalar==r.scalar;else if(eq&&(l.kind==V_STRING||l.kind==V_TEXT))eq=l.len==r.len&&!memcmp(l.data,r.data,l.len);else if(eq&&l.kind!=V_NULL)eq=0;b=in.opcode==DEUS_EQUAL?eq:!eq;}drop(&l);drop(&r);st[sp++]=(Value){V_BOOL,NULL,0,b,{0}};}
else if(in.opcode==DEUS_TO_TEXT||in.opcode==DEUS_TO_I64||in.opcode==DEUS_TO_BOOL){Value *v=&st[sp-1u];char b[32],*end=NULL;if(in.opcode==DEUS_TO_TEXT){int n;char *q;if(v->kind==V_STRING||v->kind==V_TEXT)continue;n=v->kind==V_I64?snprintf(b,sizeof(b),"%lld",(long long)v->scalar):snprintf(b,sizeof(b),"%s",v->scalar?"true":"false");q=n<0?NULL:(char*)malloc((size_t)n+1u);if(!q){rc=fail("conversion allocation failed");break;}memcpy(q,b,(size_t)n+1u);drop(v);*v=(Value){V_STRING,q,(size_t)n,0,{0}};}else if(in.opcode==DEUS_TO_I64){long long n;if(v->kind==V_I64)continue;if(v->kind==V_BOOL){v->kind=V_I64;continue;}errno=0;n=strtoll(v->data,&end,10);if(errno==ERANGE||!end||(size_t)(end-v->data)!=v->len){rc=fail("invalid I64 text");break;}drop(v);*v=(Value){V_I64,NULL,0,n,{0}};}else{int boolean;if(v->kind==V_BOOL)continue;if(v->kind==V_I64){v->kind=V_BOOL;v->scalar=v->scalar!=0;continue;}boolean=v->len==4u&&!memcmp(v->data,"true",4u)?1:v->len==5u&&!memcmp(v->data,"false",5u)?0:-1;if(boolean<0){rc=fail("invalid Bool text");break;}drop(v);*v=(Value){V_BOOL,NULL,0,boolean,{0}};}}
else if(in.opcode==DEUS_URL_ENCODE){if(!encode(&st[sp-1u])){rc=fail("URL_ENCODE expected a bounded scalar");break;}}
else if(in.opcode==DEUS_URL_JOIN){Value *l=&st[sp-2u],*r=&st[sp-1u];size_t n=l->len+r->len;char *q=n>URL_MAX?NULL:(char*)malloc(n+1u);if(!q){rc=fail("URL_JOIN exceeds URL limit or allocation failed");break;}memcpy(q,l->data,l->len);memcpy(q+l->len,r->data,r->len);q[n]=0;drop(r);drop(l);sp-=2u;st[sp++]=(Value){V_STRING,q,n,0,{0}};}
else if(in.opcode==DEUS_HUNT_VALUE){Value u=st[--sp],d;if(!hunt(&rt,u.data,u.len,&d,err,sizeof(err))){drop(&u);rc=fail(err);break;}drop(&u);st[sp++]=d;}
else if(in.opcode==DEUS_EMIT){Value v=st[--sp];char b[32];int n=0,ok=0;if(v.kind==V_TEXT||v.kind==V_STRING)ok=sink_write(out,v.data,v.len);else if(v.kind==V_NULL)ok=sink_write(out,"null",4u);else if(v.kind==V_BOOL)ok=sink_write(out,v.scalar?"true":"false",v.scalar?4u:5u);else if(v.kind==V_I64){n=snprintf(b,sizeof(b),"%lld",(long long)v.scalar);ok=n>0&&sink_write(out,b,(size_t)n);}else if(v.kind==V_MANAGED)ok=deus_value_write_json_to(&v.managed,out->write,out->context);else{drop(&v);rc=fail("EMIT cannot serialize this value");break;}drop(&v);if(!ok){rc=fail("output sink rejected EMIT");break;}}
else if(in.opcode==DEUS_HALT)break;}
while(sp)drop(&st[--sp]);
for(pc=0;pc<DEUS_MAX_LOCALS;pc++)if(bound[pc])drop(&loc[pc]);
deus_value_context_destroy(ctx);
return rc;}
int deus_vm_execute_program_with_host(const DeusProgram *p,FILE *out,const DeusHost *host){DeusOutputSink sink={DEUS_OUTPUT_ABI_VERSION,out,file_write};if(!out)return fail("output stream is required");return deus_vm_execute_program_with_sink(p,&sink,host);}
int deus_vm_execute_program_with_sink(const DeusProgram *p,const DeusOutputSink *out,const DeusHost *host){DeusExecutionOptions opt=deus_execution_options_default();return deus_vm_execute_program_with_options(p,out,host,&opt);}
int deus_vm_execute_program(const DeusProgram *p,FILE *out){return deus_vm_execute_program_with_host(p,out,NULL);}
